################################################################################
# Dockerfile.12.2.1.0.0
#
# Copyright (C) 2016 Justin Paul <justinpaulthekkan@gmail.com>
#
# @author: Justin Paul
#
# This program is free software: you can redistribute it and/or modify
# it as long as you retain the name of the original author and under
# the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################
FROM oraclelinux:7
MAINTAINER Justin Paul <justinpaulthekkan@gmail.com>

ENV SCRATCH=/tmp/scratch ORACLE_GROUP=oinstall ORACLE_USER=oracle ORACLE_HOME=/u01/app/oracle JDK_HOME=/u01/app/oracle/jdk MW_HOME=/u01/app/oracle/middleware DOMAIN_HOME=/u01/data

CMD /bin/bash

COPY jdk-8u74-linux-x64.tar.gz fmw_12.2.1.0.0_infrastructure_Disk1_1of1.zip fmw_12.2.1.0.0_wccontent_Disk1_1of1.zip p22331568_122100_Generic.zip p22541322_122100_Generic.zip ${SCRATCH}/

RUN	yum update -y -q && \
	yum install -y -q compat-libcap1 compat-libstdc++-33 \
	compat-libstdc++-33.i686 gcc gcc-c++ git glibc-devel glibc.i686 \
	ksh libaio libaio-devel libgcc.i686 libstdc++-devel \
	libstdc++.i686 make motif motif-devel numactl numactl-devel \
	ocfs2-tools sysstat unzip && \
	groupadd -g 1000 ${ORACLE_GROUP} && useradd -u 1000 -g 1000 -m ${ORACLE_USER} && \
	mkdir -p ${ORACLE_HOME} && chown -R ${ORACLE_USER}:${ORACLE_GROUP} ${SCRATCH} && \
	chown -R ${ORACLE_USER}:${ORACLE_GROUP} ${ORACLE_HOME} && mkdir -p ${DOMAIN_HOME} && \
	chown -R ${ORACLE_USER}:${ORACLE_GROUP} ${DOMAIN_HOME} && \
	su - -c "git clone --branch v1.0.1 https://github.com/justinpaulthekkan/oracle-fmw-tooling.git ~/scripts" ${ORACLE_USER} && \
	su - -c "/usr/bin/python ~/scripts/main.py -ip -l ${SCRATCH} -o ${ORACLE_HOME} -j ${JDK_HOME} -f ${MW_HOME} wls wcc" ${ORACLE_USER} && \
	rm -rf ${SCRATCH}
