################################################################################
# Dockerfile.database.xe.11.2.0.1.0
#
# Copyright (C) 2016 Justin Paul <justinpaulthekkan@gmail.com>
#
# @author: Justin Paul
#
# This program is free software: you can redistribute it and/or modify
# it as long as you retain the name of the original author and under
# the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################
FROM oraclelinux:7
MAINTAINER Justin Paul <justinpaulthekkan@gmail.com>

ENV PASSWORD welcome1

COPY xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip /tmp/db/

RUN	yum update -y -q && \
    yum install -y -q bc binutils gcc git glibc libaio make \
    net-tools psmisc sysstat unzip && \
    unzip -qq /tmp/db/oracle-xe-11.2.0-1.0.x86_64.rpm.zip -d /tmp/db && \

